### ISSUE TITLE
Getting pm-creds command not found

### ISSUE THREAD

**Issue by istellino-chub** [nuttmeister/pm-creds#7]
When running pm-creds command in MacOs I am getting command not found even after adding pm-creds to the PATH variable. Any ideas?

**Comment by nuttmeister** [comment]
If you have go installed (including the go bin folder in your PATH) you can `cd pm-creds && go install`.

Did you start a new shell after updating the PATH var also? Or perhaps forgot to run `go build` so there is no binary built? But easiest is maybe to try the above solution first.

**Comment by istellino-chub** [comment]
yes it is generating the binary because I can invoke it using the full PATH to the pm-creds and works like that but not doing `pm-creds` only

**Comment by nuttmeister** [comment]
Then it has not been added properly to your PATH environment, since it's the PATH variable that controls this behaviour. Or if you're in Windows this procedure might be different from what is explained in the readme.

And you will need to add it to your .zshrc, .bashrc file to have it added each time your start a new shell.

Such as:
```
export PATH="/your/path/to/pm-creds-bin-folder:$PATH"
```

**Comment by istellino-chub** [comment]
Yes I actually see the path doing a `echo $PATH` but still not working. The path is `$HOME/pm-creds/pm-creds/pm-creds`

**Comment by nuttmeister** [comment]
Is that the path to your directly where the `pm-creds` bin folder is located? It looks like it's an absolute path to the binary file. It should only to the folder, and not the binary. So perhaps try changing it to `$HOME/pm-creds/pm-creds:$PATH`

**Comment by istellino-chub** [comment]
> Is that the path to your directly where the `pm-creds` bin folder is located? It looks like it's an absolute path to the binary file. It should only to the folder, and not the binary. So perhaps try changing it to `$HOME/pm-creds/pm-creds:$PATH`

That works fine! thanks!
